// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using ToDo.ToDoClient.Api;
using ToDo.ToDoClient.ConfirmEmail;
using ToDo.ToDoClient.ForgotPassword;
using ToDo.ToDoClient.Login;
using ToDo.ToDoClient.Manage;
using ToDo.ToDoClient.Refresh;
using ToDo.ToDoClient.Register;
using ToDo.ToDoClient.ResendConfirmationEmail;
using ToDo.ToDoClient.ResetPassword;
namespace ToDo.ToDoClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The api property</summary>
        public global::ToDo.ToDoClient.Api.ApiRequestBuilder Api
        {
            get => new global::ToDo.ToDoClient.Api.ApiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The confirmEmail property</summary>
        public global::ToDo.ToDoClient.ConfirmEmail.ConfirmEmailRequestBuilder ConfirmEmail
        {
            get => new global::ToDo.ToDoClient.ConfirmEmail.ConfirmEmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forgotPassword property</summary>
        public global::ToDo.ToDoClient.ForgotPassword.ForgotPasswordRequestBuilder ForgotPassword
        {
            get => new global::ToDo.ToDoClient.ForgotPassword.ForgotPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::ToDo.ToDoClient.Login.LoginRequestBuilder Login
        {
            get => new global::ToDo.ToDoClient.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The manage property</summary>
        public global::ToDo.ToDoClient.Manage.ManageRequestBuilder Manage
        {
            get => new global::ToDo.ToDoClient.Manage.ManageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::ToDo.ToDoClient.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::ToDo.ToDoClient.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::ToDo.ToDoClient.Register.RegisterRequestBuilder Register
        {
            get => new global::ToDo.ToDoClient.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resendConfirmationEmail property</summary>
        public global::ToDo.ToDoClient.ResendConfirmationEmail.ResendConfirmationEmailRequestBuilder ResendConfirmationEmail
        {
            get => new global::ToDo.ToDoClient.ResendConfirmationEmail.ResendConfirmationEmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resetPassword property</summary>
        public global::ToDo.ToDoClient.ResetPassword.ResetPasswordRequestBuilder ResetPassword
        {
            get => new global::ToDo.ToDoClient.ResetPassword.ResetPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ToDo.ToDoClient.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
