// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using ToDo.WebClient.ToDoClient.Api.Auth.User;
namespace ToDo.WebClient.ToDoClient.Api.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The user property</summary>
        public global::ToDo.WebClient.ToDoClient.Api.Auth.User.UserRequestBuilder User
        {
            get => new global::ToDo.WebClient.ToDoClient.Api.Auth.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ToDo.WebClient.ToDoClient.Api.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ToDo.WebClient.ToDoClient.Api.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
