// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using ToDo.ToDoClient.Models;
namespace ToDo.ToDoClient.Api.TodoItems.Paged
{
    /// <summary>
    /// Builds and executes requests for operations under \api\TodoItems\paged
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PagedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ToDo.ToDoClient.Api.TodoItems.Paged.PagedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PagedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/TodoItems/paged{?Cursor*,Limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ToDo.ToDoClient.Api.TodoItems.Paged.PagedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PagedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/TodoItems/paged{?Cursor*,Limit*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::ToDo.ToDoClient.Models.TodoItemDtoPaginatedResultDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ToDo.ToDoClient.Models.TodoItemDtoPaginatedResultDto?> GetAsync(Action<RequestConfiguration<global::ToDo.ToDoClient.Api.TodoItems.Paged.PagedRequestBuilder.PagedRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ToDo.ToDoClient.Models.TodoItemDtoPaginatedResultDto> GetAsync(Action<RequestConfiguration<global::ToDo.ToDoClient.Api.TodoItems.Paged.PagedRequestBuilder.PagedRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ToDo.ToDoClient.Models.TodoItemDtoPaginatedResultDto>(requestInfo, global::ToDo.ToDoClient.Models.TodoItemDtoPaginatedResultDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ToDo.ToDoClient.Api.TodoItems.Paged.PagedRequestBuilder.PagedRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ToDo.ToDoClient.Api.TodoItems.Paged.PagedRequestBuilder.PagedRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ToDo.ToDoClient.Api.TodoItems.Paged.PagedRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ToDo.ToDoClient.Api.TodoItems.Paged.PagedRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ToDo.ToDoClient.Api.TodoItems.Paged.PagedRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class PagedRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Cursor { get; set; }
#nullable restore
#else
            public string Cursor { get; set; }
#endif
            public int? Limit { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PagedRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ToDo.ToDoClient.Api.TodoItems.Paged.PagedRequestBuilder.PagedRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
